name: deploy-prod
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LE_SECRET_TRES_SECRET_HOSTHOST }}
          username: ${{ secrets.LE_SECRET_TRES_SECRET_USERUSER }}
          password: ${{ secrets.LE_SECRET_TRES_SECRET_PASSPASS }}
          port: ${{ secrets.LE_SECRET_TRES_SECRET_PORT }}
          script: |
            cd /var/www/html/page_html
            git fetch 
            git pull origin master